---
title: "find briers"
output: html_document
date: "2025-03-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(stringr)
```



```{r}

```


```{r}

make_combined_df <- function(run_name, merge = TRUE){
  
  path_to_data <- '../data/custom_datasets'
  
  k_schemes <- read.csv(file.path(path_to_data, 'k_schemes', paste0('gridsearch_', run_name, '.csv')),
                      row.names = 1)


  path_to_gridsearch_res_dirs <- file.path(path_to_data, 'grid_search_res', run_name)
  res_dirs_names <- list.files(path_to_gridsearch_res_dirs)
  
  growing_res_df_list <- list()
  growing_kdict_df_list <- list()
  
  for(i in seq_len(length(res_dirs_names))){
    dir_name <- res_dirs_names[i]

    splits <- str_split(dir_name, pattern = '_')[[1]]
    k_dict_num <- as.integer(splits[length(splits)])
    
    growing_kdict_df_list[[i]] <- k_schemes[k_dict_num+1, 1:3]
    
    res_path <- file.path(path_to_gridsearch_res_dirs, dir_name, 'DIFFS', 'grid_search_res.csv')
    res_df <- read.csv(res_path, row.names = 1)
    growing_res_df_list[[i]] <- res_df
  }
  
  stacked_res_df <- as.data.frame(do.call(rbind, growing_res_df_list))
  stacked_kdict <- as.data.frame(do.call(rbind, growing_kdict_df_list))
  
  if(merge){
    # comb_df <- data.frame(cbind(k_schemes[seq_len(nrow(stacked_res_df)), ], stacked_res_df))
    comb_df <- data.frame(cbind(stacked_kdict, stacked_res_df))
    
  } else{
    comb_df <- stacked_res_df
  }
  
  
  comb_df <- comb_df %>%
    arrange(X5)
  
  return(comb_df)
}



```







